Support multiple maps in training
vwxyzjn/gym-microrts pull request #73
Opened 2022-03-15 14:24 UTC by xluox

Resolve #72 
Swapping maps in the vec_evn file every time a match is finished. Evaluation will not trigger swapping maps.

2022-03-15 21:19 UTC, vwxyzjn requested changes

2022-03-15 21:50 UTC, xluox commented on gym_microrts/envs/vec_env.py
> +    "/home/yifuli/Documents/gym-microrts/gym_microrts/microrts/maps/16x16/basesWorkers16x16C.xml",
Not sure how to add these codes.

2022-03-15 21:57 UTC, vwxyzjn commented on gym_microrts/envs/vec_env.py
> +    "/home/yifuli/Documents/gym-microrts/gym_microrts/microrts/maps/16x16/basesWorkers16x16C.xml",
Try print out `os.path.join(gym_microrts.__path__[0], "microrts")` see if it helps.

2022-03-15 21:58 UTC, vwxyzjn commented on gym_microrts/envs/vec_env.py
> +    "/home/yifuli/Documents/gym-microrts/gym_microrts/microrts/maps/16x16/basesWorkers16x16C.xml",
```
>>> import gym_microrts
>>> import os
>>> print(os.path.join(gym_microrts.__path__[0], "microrts"))
/home/costa/Documents/go/src/github.com/gym-microrts/gym_microrts/microrts
```

2022-03-15 22:03 UTC, xluox commented on gym_microrts/envs/vec_env.py
> +    "/home/yifuli/Documents/gym-microrts/gym_microrts/microrts/maps/16x16/basesWorkers16x16C.xml",
Got it

2022-03-18 13:55 UTC, vwxyzjn approved these changes
This makes sense to me. Thank you! Feel free to click the merge button :)

2022-03-18 14:24 UTC, merged